-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 17:36:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CRM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CRM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CRM` DEFAULT CHARACTER SET utf8 ;
USE `CRM` ;

-- -----------------------------------------------------
-- Table `CRM`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`rating` (
  `idrating` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrating`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC),
  UNIQUE INDEX `idrating_UNIQUE` (`idrating` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`salesTerritory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`salesTerritory` (
  `idsalesterritory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsalesterritory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idsalesterritory_UNIQUE` (`idsalesterritory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`company` (
  `idcompany` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `NPA` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `salesterritory_idsalesterritory` INT NOT NULL,
  `rating_idrating` INT NOT NULL,
  PRIMARY KEY (`idcompany`),
  INDEX `fk_company_rating_idx` (`rating_idrating` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_company_region1_idx` (`salesterritory_idsalesterritory` ASC),
  UNIQUE INDEX `idcompany_UNIQUE` (`idcompany` ASC),
  CONSTRAINT `fk_company_rating`
    FOREIGN KEY (`rating_idrating`)
    REFERENCES `CRM`.`rating` (`idrating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_region1`
    FOREIGN KEY (`salesterritory_idsalesterritory`)
    REFERENCES `CRM`.`salesTerritory` (`idsalesterritory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`machine` (
  `idmachine` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`idmachine`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idmachine_UNIQUE` (`idmachine` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`machine_has_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`machine_has_company` (
  `machine_idmachine` INT NOT NULL,
  `company_idcompany` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`machine_idmachine`, `company_idcompany`),
  INDEX `fk_machine_has_company_company1_idx` (`company_idcompany` ASC),
  INDEX `fk_machine_has_company_machine1_idx` (`machine_idmachine` ASC),
  CONSTRAINT `fk_machine_has_company_machine1`
    FOREIGN KEY (`machine_idmachine`)
    REFERENCES `CRM`.`machine` (`idmachine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_machine_has_company_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `CRM`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC),
  UNIQUE INDEX `idstatus_UNIQUE` (`idstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`offer` (
  `idoffer` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(2048) NULL,
  `date` DATE NOT NULL,
  `status_idstatus` INT NOT NULL,
  `company_idcompany` INT NOT NULL,
  `discount` INT NULL DEFAULT 0,
  PRIMARY KEY (`idoffer`, `company_idcompany`),
  INDEX `fk_offer_company1_idx` (`company_idcompany` ASC),
  INDEX `fk_offer_Status1_idx` (`status_idstatus` ASC),
  UNIQUE INDEX `idoffer_UNIQUE` (`idoffer` ASC),
  CONSTRAINT `fk_offer_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `CRM`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_Status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `CRM`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`offer_has_machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`offer_has_machine` (
  `offer_idoffer` INT NOT NULL,
  `machine_idmachine` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`offer_idoffer`, `machine_idmachine`),
  INDEX `fk_offer_has_machine_machine1_idx` (`machine_idmachine` ASC),
  INDEX `fk_offer_has_machine_offer1_idx` (`offer_idoffer` ASC),
  CONSTRAINT `fk_offer_has_machine_offer1`
    FOREIGN KEY (`offer_idoffer`)
    REFERENCES `CRM`.`offer` (`idoffer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_has_machine_machine1`
    FOREIGN KEY (`machine_idmachine`)
    REFERENCES `CRM`.`machine` (`idmachine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`function` (
  `idfunction` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfunction`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idfunction_UNIQUE` (`idfunction` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `company_idcompany` INT NOT NULL,
  `function_idfunction` INT NOT NULL,
  PRIMARY KEY (`idcontact`, `company_idcompany`),
  INDEX `fk_contact_company1_idx` (`company_idcompany` ASC),
  UNIQUE INDEX `uk_name` (`firstname` ASC, `lastname` ASC),
  INDEX `fk_contact_function1_idx` (`function_idfunction` ASC),
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC),
  CONSTRAINT `fk_contact_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `CRM`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_function1`
    FOREIGN KEY (`function_idfunction`)
    REFERENCES `CRM`.`function` (`idfunction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype`),
  UNIQUE INDEX `vaue_UNIQUE` (`value` ASC),
  UNIQUE INDEX `idtype_UNIQUE` (`idtype` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`event` (
  `idevent` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `decription` VARCHAR(2048) NULL,
  `company_idcompany` INT NOT NULL,
  `type_idtype` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idevent`, `company_idcompany`),
  INDEX `fk_event_company1_idx` (`company_idcompany` ASC),
  INDEX `fk_event_type1_idx` (`type_idtype` ASC),
  UNIQUE INDEX `idevent_UNIQUE` (`idevent` ASC),
  CONSTRAINT `fk_event_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `CRM`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `CRM`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`contact_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`contact_has_event` (
  `contact_idcontact` INT NOT NULL,
  `event_idevent` INT NOT NULL,
  PRIMARY KEY (`contact_idcontact`, `event_idevent`),
  INDEX `fk_contact_has_event_event1_idx` (`event_idevent` ASC),
  INDEX `fk_contact_has_event_contact1_idx` (`contact_idcontact` ASC),
  CONSTRAINT `fk_contact_has_event_contact1`
    FOREIGN KEY (`contact_idcontact`)
    REFERENCES `CRM`.`contact` (`idcontact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_has_event_event1`
    FOREIGN KEY (`event_idevent`)
    REFERENCES `CRM`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`competitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`competitor` (
  `idCompetitor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompetitor`),
  UNIQUE INDEX `idCompetitors_UNIQUE` (`idCompetitor` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`machineCompetitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`machineCompetitor` (
  `idmachineCompetitor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Competitor_idCompetitor` INT NOT NULL,
  PRIMARY KEY (`idmachineCompetitor`, `Competitor_idCompetitor`),
  UNIQUE INDEX `idmachineCompetitors_UNIQUE` (`idmachineCompetitor` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_machineCompetitors_Competitors1_idx` (`Competitor_idCompetitor` ASC),
  CONSTRAINT `fk_machineCompetitors_Competitors1`
    FOREIGN KEY (`Competitor_idCompetitor`)
    REFERENCES `CRM`.`competitor` (`idCompetitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`company_has_machineCompetitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`company_has_machineCompetitor` (
  `company_idcompany` INT NOT NULL,
  `machineCompetitor_idmachineCompetitor` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`company_idcompany`, `machineCompetitor_idmachineCompetitor`),
  INDEX `fk_company_has_machineCompetitors_machineCompetitors1_idx` (`machineCompetitor_idmachineCompetitor` ASC),
  INDEX `fk_company_has_machineCompetitors_company1_idx` (`company_idcompany` ASC),
  CONSTRAINT `fk_company_has_machineCompetitors_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `CRM`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_has_machineCompetitors_machineCompetitors1`
    FOREIGN KEY (`machineCompetitor_idmachineCompetitor`)
    REFERENCES `CRM`.`machineCompetitor` (`idmachineCompetitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`userCB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`userCB` (
  `iduserCB` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `skypeCode` VARCHAR(255) NULL,
  `isApproved` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`iduserCB`),
  UNIQUE INDEX `iduserCB_UNIQUE` (`iduserCB` ASC),
  UNIQUE INDEX `skypeCode_UNIQUE` (`skypeCode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`logsCB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`logsCB` (
  `idlogsCB` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `message` VARCHAR(5000) NULL,
  `intent` VARCHAR(200) NULL,
  `entities` VARCHAR(500) NULL,
  `contextes` VARCHAR(5000) NULL,
  `response` VARCHAR(5000) NULL,
  `userCB_iduserCB` INT NOT NULL,
  PRIMARY KEY (`idlogsCB`, `userCB_iduserCB`),
  UNIQUE INDEX `idLogsCB_UNIQUE` (`idlogsCB` ASC),
  INDEX `fk_LogsCB_userCB1_idx` (`userCB_iduserCB` ASC),
  CONSTRAINT `fk_LogsCB_userCB1`
    FOREIGN KEY (`userCB_iduserCB`)
    REFERENCES `CRM`.`userCB` (`iduserCB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM`.`errorCB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM`.`errorCB` (
  `iderrorCB` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `message` VARCHAR(5000) NULL,
  `intent` VARCHAR(500) NULL,
  `entities` VARCHAR(500) NULL,
  `contextes` VARCHAR(5000) NULL,
  `error` VARCHAR(5000) NULL,
  `userCB_iduserCB` INT NOT NULL,
  PRIMARY KEY (`iderrorCB`, `userCB_iduserCB`),
  INDEX `fk_errorCB_userCB1_idx` (`userCB_iduserCB` ASC),
  CONSTRAINT `fk_errorCB_userCB1`
    FOREIGN KEY (`userCB_iduserCB`)
    REFERENCES `CRM`.`userCB` (`iduserCB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
